cc_binary(
    name = "day1",
    srcs = [
        "day1.cpp", 
        "common/main.cpp"
    ],
)

cc_binary(
    name = "day2",
    srcs = [
        "day2.cpp", 
        "common/main.cpp"
    ],
)

cc_binary(
    name = "day3",
    srcs = [
        "day3.cpp", 
        "common/main.cpp"
    ],
)

cc_binary(
    name = "day4",
    srcs = [
        "day4.cpp", 
        "common/main.cpp"
    ],
)
